name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Print Files
      run: ls -l
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack Standalone
      run: zip ./Team123it.Arcaea.MarveCube.Standalone.zip ./Team123it.Arcaea.MarveCube.Standalone/bin
    - name: Pack main
      run: zip ./Team123it.Arcaea.MarveCube.zip ./Team123it.Arcaea.MarveCube/bin
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Team123it.Arcaea.MarveCube.zip
          Team123it.Arcaea.MarveCube.Standalone.zip
        
